[target.x86_64-unknown-linux-gnu]
pre-build = [
    "apt-get update && apt-get install -y pkg-config libdbus-1-dev libssl-dev"
]
zig = "2.17"

[target.x86_64-pc-windows-gnu]
pre-build = [
    "apt-get update && apt-get install -y pkg-config libdbus-1-dev libssl-dev"
]

[target.aarch64-unknown-linux-gnu]
dockerfile = "./docker/Dockerfile.aarch64-unknown-linux-gnu"
zig = "2.17"

[target.armv7-unknown-linux-gnueabihf]
dockerfile = "./docker/Dockerfile.armv7-unknown-linux-gnueabihf"
zig = "2.17"
